version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"  # Maps container's port 80 to localhost:8080
    volumes:
      - .:/var/www/html  # Mount source code (for dev mode)
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ecommerce_db
      DB_USER: ecommerce_user
      DB_PASSWORD: ecommerce_pass

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
